services:
  immich-smartalbum:
    image: ghcr.io/nsheridan/immich-smartalbum:latest
    container_name: immich-smartalbum
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config.yaml:ro
